import type { AssayModuleDefinition } from "./types";

export const assayModules: AssayModuleDefinition[] = [
  {
    id: "cell-viability",
    shortName: "CCK-8 · MTT · alamarBlue",
    name: "细胞活性 / 细胞增殖",
    measurementTarget: "细胞代谢活性与相对存活/增殖",
    description: "兼容吸光、荧光等读数；统一处理空白扣除、技术复孔 QC、对照归一化和生物学重复汇总。",
    detectionModes: ["absorbance", "fluorescence", "luminescence"],
    status: "ready",
  },
  {
    id: "protein-quant",
    shortName: "BSA · BCA · Bradford",
    name: "蛋白定量",
    measurementTarget: "总蛋白浓度与蛋白吸收特征",
    description: "标准曲线、未知样本反算、稀释校正及范围外结果提示。",
    detectionModes: ["absorbance"],
    status: "ready",
  },
  {
    id: "atp-quant",
    shortName: "ATP",
    name: "ATP 发光定量",
    measurementTarget: "ATP 含量与样本能量状态",
    description: "动力学读数、峰值窗口、背景扣除、log-log 标准曲线和浓度反算。",
    detectionModes: ["luminescence"],
    status: "ready",
  },
  {
    id: "elisa",
    shortName: "ELISA",
    name: "免疫分析",
    measurementTarget: "抗原或抗体等目标物的特异性定量",
    description: "4PL / 5PL 标准曲线、浓度反算和质控样本判定。",
    detectionModes: ["absorbance", "fluorescence", "luminescence"],
    status: "planned",
  },
  {
    id: "luciferase",
    shortName: "Luciferase",
    name: "单 / 双荧光素酶",
    measurementTarget: "报告基因活性与细胞通路响应",
    description: "Firefly、Renilla、背景校正、比值归一化和 fold change。",
    detectionModes: ["luminescence"],
    status: "ready",
  },
  {
    id: "microbial-growth",
    shortName: "OD600",
    name: "微生物生长动力学",
    measurementTarget: "微生物生长与药物抑制动力学",
    description: "生长曲线、lag 期、最大生长速率、AUC 和抑菌曲线。",
    detectionModes: ["absorbance"],
    status: "planned",
  },
  {
    id: "advanced-binding",
    shortName: "TR-FRET / Alpha",
    name: "高级结合与通路实验",
    measurementTarget: "分子互作与细胞信号通路活性",
    description: "多通道比值、cAMP、激酶、蛋白互作和筛选质控。",
    detectionModes: ["fluorescence", "trf", "alpha"],
    status: "planned",
  },
];
